### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by ConrDev** [Flumsykun/Laravel-oefenen1#1]
### Structural:
- Keep code convention: `usersCoolPosts` -> `posts`, `user_id` is unneeded **UNLESS** the model and column name before the `_id` do not match with the model name https://github.com/Flumsykun/Laravel-oefenen1/blob/16f3b21dc7b6bebc0414204d6b385110ad6ffb3e/app/Models/User.php#L46-L48
- Normally we'd split these up in different blade files (for readability) and or include them in `home.blade` or give it's own route, for example i would put post list on `/posts` personally but on the home it's fine too. About the blade files, login stuff in for example `auth/login.blade` or `auth/register.blade` this way you don't have to load in all posts in the background on a auth page which is in general unneeded memory usage https://github.com/Flumsykun/Laravel-oefenen1/blob/16f3b21dc7b6bebc0414204d6b385110ad6ffb3e/resources/views/home.blade.php#L11-L130
- This is fine, but i would suggest using `Hash::make()` to keep it framework level https://github.com/Flumsykun/Laravel-oefenen1/blob/16f3b21dc7b6bebc0414204d6b385110ad6ffb3e/app/Http/Controllers/UserController.php#L39C1-L39C73
- For testing purpose, i would suggest to always seed/factory models. Example: 
> ```php
> // Seeder
> User::factory(10)->create()->each(function (User $user) { 
>     return Post::factory()->for($user)->create();
> });
> 
> // PostFactory
> return [
>     'title' => fake()->text(20),
>     'body' => fake()->paragraph(),
>     'user_id' => User::factory(), // depending on Laravel version
> ];
> ```
This way you always have data to test with and you can edit or add more to them depending on what your testing
https://github.com/Flumsykun/Laravel-oefenen1/blob/16f3b21dc7b6bebc0414204d6b385110ad6ffb3e/database/seeders/DatabaseSeeder.php#L13-L21

### Personal opinion _(which some would share the same opinion)_:
- I suggest you to use `foreignIdFor`, this way you can give it a model instead of an column name, column name will be generate for you, this just makes it easier to type and read https://github.com/Flumsykun/Laravel-oefenen1/blob/16f3b21dc7b6bebc0414204d6b385110ad6ffb3e/database/migrations/2024_01_09_145145_create_posts_table.php#L18C21-L18C21

### Cleanup:
- `: HasMany` after function https://github.com/Flumsykun/Laravel-oefenen1/blob/16f3b21dc7b6bebc0414204d6b385110ad6ffb3e/app/Models/Post.php#L18-L20 https://github.com/Flumsykun/Laravel-oefenen1/blob/16f3b21dc7b6bebc0414204d6b385110ad6ffb3e/app/Models/User.php#L46-L48

**Comment by ConrDev** [comment]
Overall: Good work, see that you learned and that you fixed and cleaned up the things that were wrong. Only thing you have to do is work on readability and read more docs to understand the structural functions more than you already do on some level.

**Comment by Flumsykun** [comment]
Thanks for the feedback
